# Generated by Django 4.1.1 on 2023-07-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_customer_menuitems_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customerId',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='menuItem',
            new_name='menuItemId',
        ),
    ]
