# Generated by Django 4.1.1 on 2023-07-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_customer_order_customerid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='tableId',
            new_name='table_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customerId',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='menuItemId',
            new_name='item_id',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('customer_id', 'item_id'), name='unique_customer_item_combination'),
        ),
    ]
